version: '3.7'

services:
  airflow:
    build: .
    ports:
      - "8080:8080"
      - "8793:8793"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./plugins:/opt/airflow/plugins
      - ./config:/opt/airflow/config
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://<user>:<password>@<host>:<port>/<database>
      - AIRFLOW__WEBSERVER__SECRET_KEY=mysecretkey
      - AIRFLOW__WEBSERVER__WEB_SERVER_PORT=8080
      - AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL=30
      - AIRFLOW__SCHEDULER__SCHEDULER_HEARTBEAT_SEC=10
      - AIRFLOW__SCHEDULER__SCHEDULER_RUNS_DEDICATED_THREAD=True
      - AIRFLOW__SCHEDULER__MAX_THREADS=2
      - AIRFLOW__SCHEDULER__ORPHANED_TASKS_CHECK_INTERVAL_SEC=300
      - AIRFLOW__SCHEDULER__CATCHUP_BY_DEFAULT=False
      - AIRFLOW__SCHEDULER__DAGS_ARE_PAUSED_AT_CREATION=True
      - AIRFLOW__SCHEDULER__SCHEDULE_AFTER_TASK_EXECUTION=True
      - AIRFLOW__SCHEDULER__JOB_HEARTBEAT_SEC=1

  postgres:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: <user>
      POSTGRES_PASSWORD: <password>
      POSTGRES_DB: <database>
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

