# Connection information for a PostgreSQL database
my_postgres_conn:
  conn_type: postgres
  host: <host>
  port: <port>
  login: <user>
  password: <password>
  schema: <schema>
  
# Connection information for an S3 bucket
my_s3_conn:
  conn_type: s3
  login: <access_key_id>
  password: <secret_access_key>
  host: s3.amazonaws.com
  
# Connection information for a MySQL database
my_mysql_conn:
  conn_type: mysql
  host: <host>
  port: <port>
  login: <user>
  password: <password>
  schema: <schema>
